#INITIAL SETTINGS
data_source: "http://127.0.0.1:8000/api/v1/datas/" #"http://data_service:8000/api/v1/datas/"  #"http://baby-j-data-service.herokuapp.com/api/v1/datas/" #   
data_mod: "http://127.0.0.1:8000/api/v1/up_data/"  #"http://data_service:8000/api/v1/up_data/" # "http://baby-j-data-service.herokuapp.com/api/v1/up_data/" # 

LOADING_OPTIONS:
  local: "http://127.0.0.1:8000/api/v1/datas/"
  local_docker: "http://data_service:8000/api/v1/datas/"
  heroku: "http://baby-j-data-service.herokuapp.com/api/v1/datas/"   
